### ISSUE TITLE
Genetics is broken

### ISSUE THREAD

**Issue by Verarch** [ErosResearchPlatform/Eros-old#105]
#### Description of issue

Genetics partially-sorta works. You are unable to change the species from human to monkey or monkey to human using block 27 on Structural Enzymes. They just remain a monkey. They adopt a human sprite if hulked or human shadow if they have thermal resistance, but no change in species mechanically.

#### Difference between expected and actual behavior

Expected: Species to change from "Monkey" to "Human
Result: Remains monkey after editing species sub-blocks.

#### Steps to reproduce 

Put monkey in DNA modifier (or anyone)
Alter block 27 in S.E. to >800 and <800
Note both values don't alter patient's species.

#### Length of time in which bug has been known to occur

Ever since genetics was re-enabled, which was a few weeks maybe. It's probably missing code.

#### Client version, Server revision & Game ID

Client Version: 511
Server Revision: Revision Unknown
Game ID: bLG-cJR6

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by RobotAlice** [comment]
Already reported by Arby. (Issue #67 )
I'm working on it now. Expect a fix in the next couple days at worst, likely tonight/tomorrow.

**Comment by ArbyTheDragon** [comment]
My report is about UI blocks and didn't include the bug about the monkeyblock in the structural enzymes. 
This bug with the monkeyblock DOES exist, I've already experienced it, and it wasn't specificly reported by me yet.

In any case, RobotAlice acknowledges its existance and is working on it.
Alice knows all about the mysteries of why the genetics code is dysfunctional. Code isn't necessarily missing, it's just broken.
Ask Alice!

**Comment by RobotAlice** [comment]
Fixed in PR#107.
