### ISSUE TITLE
Colour selection for ears, tails and wings

### ISSUE THREAD

**Issue by SecondAttemps** [ErosResearchPlatform/Eros-old#106]
#### Description of issue
When accessing the character creation screen the previee for selecting the colour of the ears, tail, or wings are too close to the above colour preview window. This can lead to confusion of what option colours what part

#### Difference between expected and actual behavior
I would expect that the options would be more spaced out, however currently they are too close to each other.

#### Steps to reproduce 
Access the character creation screen and the problem will be immediately visible.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ghost** [comment]
@silveryferret Did you toss in that spacing addition you did?

**Comment by silveryferret** [comment]
this has been fixed, forgot to close the issue
