### ISSUE TITLE
Voidsuit helmets lack spritesheet reference for humans

### ISSUE THREAD

**Issue by Yithani** [ErosResearchPlatform/Eros-old#121]
#### Description of issue
See title. Causes humans to show up as having no head overlays when they equip any item that is a subclass of /obj/item/clothing/head/helmet/space/void

#### Difference between expected and actual behavior
Humans show up as bald and beardless rather than with the correct sprite from /obj/item/clothing/head/helmet/space/void 

#### Steps to reproduce 
Be human, equip any voidsuit helmet

#### Specific information for locating

/obj/item/clothing/head/helmet/space/void and all subclasses will need 
"Human" -> icons/mob/head.dmi
to be added to their sprite_sheets variables. Not sure how this is done in the code, but that's how I fixed it ingame.

#### Length of time in which bug has been known to occur

Has been occurring, based on codediving, since https://github.com/Baystation12/Baystation12/pull/14699 was merged

#### Client version, Server revision & Game ID
Client Version: 510
Server Revision: Revision Unknown
Game ID: bLJ-ctr5

Discovered on Eros, also reported at https://github.com/Baystation12/Baystation12/issues/14728

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by silveryferret** [comment]
#125 and #129 should bandaid over the issues until we can properly fix it
