### ISSUE TITLE
Drying Rack Bug

### ISSUE THREAD

**Issue by TheLightorTheDark** [ErosResearchPlatform/Eros-old#138]
#### Description of issue
Using a satchel, backpack, or trash bag, anything can be dumped into the Drying Rack, from plants to guns. Anything incompatible with the Drying Rack simply disappears, while compatible items enter it as normal.

#### Difference between expected and actual behavior
To give an example, the Botany Satchel can be used to pick up harvested fruits, and seeds. It's possible to dump the seeds into the Garden Seed Storage, while there are Fruits in the Satchel, without the Fruits getting dumped in and disappearing. With bags and the Drying Rack, everything gets dumped in.

#### Steps to reproduce 
Acquire a satchel or backpack, put any object inside, then click on the Drying Rack with the bag to empty the contents into the Drying Rack.

#### Specific information for locating

Drying Rack, in the Garden directly East of the Kitchen.

#### Length of time in which bug has been known to occur

Only noticed during the last week.

#### Client version, Server revision & Game ID

Client Version: 510
Server Revision: 8df1670c3cefa9c7a8d32bfe9bdf5155acb83ad6 -  - 2016-11-28
Game ID: bLO-c9pv

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by RobotAlice** [comment]
Someone fixed it before I could. Welp.
