### ISSUE TITLE
All species glow when irradiated

### ISSUE THREAD

**Issue by ghost** [ErosResearchPlatform/Eros-old#144]
#### Description of issue
On the can.

#### Difference between expected and actual behavior
Prometheans should be the only ones to glow.
Assuming this is related to my spaghetti code attempt at porting promies before Zuhayr actually did.

#### Steps to reproduce 
Be a carbon mob, irradiate self, turn into flashlight.

#### Length of time in which bug has been known to occur
Unknown. If anyone knows when this started, please tell me.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by OrbisAnima** [comment]
2 days ago sent you the fix through discord
