### ISSUE TITLE
Prescription Med HUD Value

### ISSUE THREAD

**Issue by ghost** [ErosResearchPlatform/Eros-old#178]
#### Description of issue
Prescription Med HUD wasn't prescription.

#### Difference between expected and actual behavior
Prescription Medical HUD spawns with prescription = 1, as a player's loadout item, when it should have spawned with prescription = 7 to work properly.

#### Steps to reproduce 
Pick in loadout, need glasses, spawn as medical.
Have not attempted to reproduce as of yet -- will try later, and will be surprised if it isn't reliably reproduced.

#### Length of time in which bug has been known to occur
Today.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Mewchild** [comment]
I'll fix this tonight, once I'm home.

**Comment by Mewchild** [comment]
I'll fix this tonight, once I'm home.

**Comment by Mewchild** [comment]
The issue also affected Prescription sec huds. I've fixed them both
