### ISSUE TITLE
DNA Modification in Genetics- Can't transfer/save certain UI blocks!

### ISSUE THREAD

**Issue by ArbyTheDragon** [ErosResearchPlatform/Eros-old#67]
#### Description of issue
If a person is placed in a DNA Modifier Console, his or her UI and SE can be seen. You can also load this into a transfer buffer, which saves this data. From this you can create injectors from this data containing information from a certain block.

You can also transfer an entire UI or SE with the "Transfer" button

#### Difference between expected and actual behavior
You would hope the injector contains data from the block listed in the UI or SE, but for blocks 28 through 34 in the UI, they're all blank (000). If you make an injector for one of these blocks, the data in the injector will be 000 ALWAYS. If you do a transfer to another body, the UI will contain 000 in those blocks.

This is confirmed to be a problem with multiple people, from mouse ears to an ordinary Unathi. Screenshots here.
http://puu.sh/s1bSQ/493a1b947c.png
http://puu.sh/s1j1V/002c78ebd4.png
http://puu.sh/s1kOV/34f3e09ac6.png
These were real characters who were not cloned. They are differing in appearance. The data contained in UI DIRECTLY determines appearance of the character in the round.. Their UI was copied to a buffer and the menu on the right is for making block injectors. The blocks 28-34 are shown as 000 regardless of the data contained in the UI. 

#### Steps to reproduce 
Find someone with ears with colors, or anything that has modifications to blocks 28 through 34.
Notice how you can't transfer those specific blocks properly. Whatever you do, the value you get out of a block 28 through 34 in the UI will come out as 000.

#### Specific information for locating

Read the block information carefully when you select a block to make an injector of. Or transfer the entire UI of a person who has changes to these blocks and notice how the clone/unmonkey differs from the person you took the UI from. http://puu.sh/s1leS/dc93f975d8.png

#### Length of time in which bug has been known to occur

Discovered October 30th, 2016.

#### Client version, Server revision & Game ID

Client Version 510
Unknown server reversion. But would be the git used on 9:00PM CDT, October 30th, 2016
Game ID: bLk-aiiX

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ArbyTheDragon** [comment]
It happens that the maximum length of the SE buffer is 27. Maybe there is something going on in "buffer.len" in (Eros/code/game/dna/dna_modifier.dm) that reads a domain width of 27 from the SE part of (Eros/code/game/dna/dna2.dm) instead of the intended 34 for UI. 
Maybe the length of the SE is obeyed for the UI, causing this bug. 

_Is it not a coincidence that only the first 27 blocks are stored, and blocks 28 and up are left as 000?_

**Comment by RobotAlice** [comment]
Fixed in PR#107.
