### ISSUE TITLE
Cargo Manifest Issue

### ISSUE THREAD

**Issue by AliciaJewel** [ErosResearchPlatform/Eros-old#80]
#### Description of issue

Cargo Technicians and Quartermasters appear under both the Civilian and Cargo sections of the Crew Manifest, but Shaft Miners only appear under Civilian.

#### Steps to reproduce 

1. Have any of the above-listed jobs on the station.
2. Check the manifest.
3. See that they are exactly where I described above.

#### Length of time in which bug has been known to occur

Since November 3rd.

#### Client version, Server revision & Game ID

Client Version: 510
Server Revision: Revision Unknown
Game ID: bLp-dla5

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ArbyTheDragon** [comment]
I think I recall this in the manifest. It made me like O-o?. 
You can check the "Reproduced by different players" box.
